//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0241506_EczCVEntities : DbContext
    {
        public u0241506_EczCVEntities()
            : base("name=u0241506_EczCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CVAdmin> CVAdmin { get; set; }
        public virtual DbSet<TFacts> TFacts { get; set; }
        public virtual DbSet<THome> THome { get; set; }
        public virtual DbSet<TPortfolio2> TPortfolio2 { get; set; }
        public virtual DbSet<TResume1> TResume1 { get; set; }
        public virtual DbSet<TSkills> TSkills { get; set; }
        public virtual DbSet<TLinks> TLinks { get; set; }
        public virtual DbSet<TContact> TContact { get; set; }
        public virtual DbSet<TMessages> TMessages { get; set; }
        public virtual DbSet<TAbout> TAbout { get; set; }
        public virtual DbSet<TServices> TServices { get; set; }
        public virtual DbSet<TResume2> TResume2 { get; set; }
        public virtual DbSet<TPortfolio1> TPortfolio1 { get; set; }
    }
}
