//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAbout
    {
        public byte ID { get; set; }
        public string Image { get; set; }
        public string DescTitle { get; set; }
        public string Description { get; set; }
        public string Birth { get; set; }
        public string WebSite { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Age { get; set; }
        public string Degree { get; set; }
        public string Email { get; set; }
        public string Freelance { get; set; }
        public string LastDescription { get; set; }
    }
}
