//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TServices
    {
        public byte ID { get; set; }
        public string Description { get; set; }
        public string Title1 { get; set; }
        public string TDesc1 { get; set; }
        public string Title2 { get; set; }
        public string TDesc2 { get; set; }
        public string Title3 { get; set; }
        public string TDesc3 { get; set; }
        public string Title4 { get; set; }
        public string TDesc4 { get; set; }
        public string Title5 { get; set; }
        public string TDesc5 { get; set; }
        public string Title6 { get; set; }
        public string TDesc6 { get; set; }
        public string Title7 { get; set; }
        public string TDesc7 { get; set; }
        public string Title8 { get; set; }
        public string TDesc8 { get; set; }
        public string Title9 { get; set; }
        public string TDesc9 { get; set; }
        public string Title10 { get; set; }
        public string TDesc10 { get; set; }
        public string Title11 { get; set; }
        public string TDesc11 { get; set; }
        public string Title12 { get; set; }
        public string TDesc12 { get; set; }
    }
}
