//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSkills
    {
        public byte ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Num1 { get; set; }
        public string Title1 { get; set; }
        public Nullable<int> Num2 { get; set; }
        public string Title2 { get; set; }
        public Nullable<int> Num3 { get; set; }
        public string Title3 { get; set; }
        public Nullable<int> Num4 { get; set; }
        public string Title4 { get; set; }
        public Nullable<int> Num5 { get; set; }
        public string Title5 { get; set; }
        public Nullable<int> Num6 { get; set; }
        public string Title6 { get; set; }
    }
}
